packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - better-sqlite3
  - scrypt
  - sha3

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - keccak
  - secp256k1
  - websocket
